version: '3.5'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: smart-home
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - app
    restart: unless-stopped


  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - app
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/pwfile.txt:/mosquitto/config/pwfile.txt

  influxdb:
    image: influxdb:latest
    volumes:
      - /var/lib/influxdb2
    ports:
      - "8086:8086"
    networks:
      - app

  spring-boot-app-1:
    image: ftn/smart-home:latest
    ports:
      - "1111:1111"
    depends_on:
      - mosquitto
      - postgres
      - influxdb
    networks:
      - app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      MQTT_HOST: mosquitto
      INFLUXDB_HOST: influxdb
      SERVER_PORT: 1111
      TEMPFOLDER_PATH: tmp/temp

  spring-boot-app-2:
    image: ftn/smart-home:latest
    ports:
      - "2222:2222"
    depends_on:
      - mosquitto
      - postgres
      - influxdb
    networks:
      - app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      MQTT_HOST: mosquitto
      INFLUXDB_HOST: influxdb
      SERVER_PORT: 2222
      TEMPFOLDER_PATH: tmp/temp

  spring-boot-app-3:
    image: ftn/smart-home:latest
    ports:
      - "3333:3333"
    depends_on:
      - mosquitto
      - postgres
      - influxdb
    networks:
      - app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      MQTT_HOST: mosquitto
      INFLUXDB_HOST: influxdb
      SERVER_PORT: 3333
      TEMPFOLDER_PATH: tmp/temp
      
  spring-boot-simulator:
    image: ftn/smart-home-simulator:latest
    ports:
      - "9999:9999"
    depends_on:
      - mosquitto
      - postgres
      - spring-boot-app-1
      - spring-boot-app-2
      - spring-boot-app-3
    networks:
      - app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      MQTT_HOST: mosquitto

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - spring-boot-app-1
      - spring-boot-app-2
      - spring-boot-app-3
    volumes:
      - ./nginx/conf/nginx_docker.conf:/etc/nginx/nginx.conf
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  postgres: