export enum WashingMachineMode {
    COTTONS = "COTTONS", SYNTHETICS = "SYNTHETICS", DAILY_EXPRESS = "DAILY_EXPRESS", WOOL = "WOOL",
    DARK_WASH = "DARK_WASH", OUTDOOR = "OUTDOOR", SHIRTS = "SHIRTS", DUVET = "DUVET", MIXED = "MIXED",
    STEAM = "STEAM", RINSE_SPIN = "RINSE_SPIN", SPIN_ONLY = "SPIN_ONLY", HYGIENE = "HYGIENE"
}