INSERT INTO ROLE (NAME) VALUES('ROLE_SUPERADMIN') ON CONFLICT (NAME) DO NOTHING;
INSERT INTO ROLE (NAME) VALUES('ROLE_ADMIN') ON CONFLICT (NAME) DO NOTHING;
INSERT INTO ROLE (NAME) VALUES('ROLE_USER') ON CONFLICT (NAME) DO NOTHING;
INSERT INTO PROPERTIES (ID, NAME) VALUES(1, 'Yes') ON CONFLICT (ID) DO NOTHING;