package com.ftn.uns.ac.rs.smarthomesimulator.models.enums;

public enum WMState {

    ON, OFF, COTTONS_MODE, SYNTHETICS_MODE, DAILY_EXPRESS_MODE, WOOL_MODE, DARK_WASH_MODE,
    OUTDOOR_MODE, SHIRTS_MODE, DUVET_MODE, MIXED_MODE, STEAM_MODE, RINSE_SPIN_MODE, SPIN_ONLY_MODE, HYGIENE_MODE,
    SCHEDULE_ON, SCHEDULE_OFF, SCHEDULE, CANCEL_SCHEDULED
}
